(function(){var v,i,w=this,q=new String("string"),s=w.document,z=/^#([\w-]+)$/;w.x$=w.xui=i=function(e,a){return new i.fn.find(e,a)};if(!Array.prototype.forEach)Array.prototype.forEach=function(e,a){var b=this.length||0;if(typeof e=="function")for(var c=0;c<b;c++)e.call(a,this[c],c,this)};i.fn=i.prototype={elements:[],extend:function(e){for(var a in e)i.fn[a]=e[a]},find:function(e,a){var b=[];this.cache=a;if(a==v&&this.elements.length)return i(e,this.elements);else a=s;b=typeof e==q&&z.test(e)?[a.getElementById(e.substr(1))]:
typeof e==q?Array.prototype.slice.call(a.querySelectorAll(e)):[e];this.elements=this.reduce(b);return this},reduce:function(e,a){var b=[];e.forEach(function(c){b.indexOf(c,0,a)<0&&b.push(c)});return b},removex:function(e,a,b){b=e.slice((b||a)+1||e.length);e.length=a<0?e.length+a:a;return e.push.apply(e,b)},has:function(e){var a=[];this.each(function(b){i(e).each(function(c){c==b&&a.push(b)})});this.elements=a;return this},not:function(e){var a=this.elements,b;for(b=0;b<a.length;b++)i(e).each(function(c){if(a[b]==
c)this.elements=this.removex(a,a.indexOf(a[b]))});return this},each:function(e){for(var a=0,b=this.elements.length;a<b;++a)if(e.call(this.elements[a],this.elements[a],a,this)===false)break;return this}};i.fn.find.prototype=i.fn;i.extend=i.fn.extend;i.extend({html:function(e,a){var b=function(d){if(d.firstChild===null)switch(d.tagName){case "UL":return"LI";case "DL":return"DT";case "TR":return"TD";default:return d.tagName}return d.firstChild.tagName},c=function(d,f){var o={},l=/^<([A-Z][A-Z0-9]*)([^>]*)>(.*)<\/\1>/i;
if(l.test(d)){result=l.exec(d);f=result[1];if(result[2]!==""){d=result[2].split(/([A-Z]*\s*=\s*['|"][A-Z0-9:;#\s]*['|"])/i);for(l=0;l<d.length;l++){var p=d[l].replace(/^\s*|\s*$/g,"");if(p!==""&&p!==" "){p=p.split("=");o[p[0]]=p[1].replace(/(["']?)/g,"")}}}d=result[3]}f=s.createElement(f);for(var g in o){l=s.createAttribute(g);l.nodeValue=o[g];f.setAttributeNode(l)}f.innerHTML=d;return f};this.clean();if(arguments.length==0)return this.elements[0].innerHTML;if(arguments.length==1&&arguments[0]!="remove"){a=
e;e="inner"}this.each(function(d){switch(e){case "inner":if(typeof a==q){d.innerHTML=a;d=d.getElementsByTagName("SCRIPT");for(var f=d.length,o=0;o<f;o++)eval(d[o].text)}else{d.innerHTML="";d.appendChild(a)}break;case "outer":if(typeof a==q)a=c(a,b(d));d.parentNode.replaceChild(a,d);break;case "top":if(typeof a==q)a=c(a,b(d));d.insertBefore(a,d.firstChild);break;case "bottom":if(typeof a==q)a=c(a,b(d));d.insertBefore(a,null);break;case "remove":f=d.parentNode;f.removeChild(d);break;case "before":f=
d.parentNode;if(typeof a==q)a=c(a,b(f));f.insertBefore(a,d);break;case "after":f=d.parentNode;if(typeof a==q)a=c(a,b(f));f.insertBefore(a,d.nextSibling);break}});return this},clean:function(){var e=/\S/;this.each(function(a){for(var b=a.firstChild,c=-1;b;){var d=b.nextSibling;if(b.nodeType==3&&!e.test(b.nodeValue))a.removeChild(b);else b.nodeIndex=++c;b=d}});return this},attr:function(e,a){if(arguments.length==2){this.each(function(c){c.setAttribute(e,a)});return this}else{var b=[];this.each(function(c){c.getAttribute(e)!=
null&&b.push(c.getAttribute(e))});return b}}});i.extend({on:function(e,a){this.each(function(b){w.addEventListener&&b.addEventListener(e,a,false)});return this}});i.extend({tween:function(e,a){this.each(function(b){emile(b,e,a)});return this}});(function(){i.extend({setStyle:function(b,c){this.each(function(d){d.style[b]=c});return this},getStyle:function(b,c){var d=function(f,o){return s.defaultView.getComputedStyle(f,"").getPropertyValue(o)};if(c===v)return d(this.elements[0],b);this.each(function(f){c(d(f,
b))});return this},addClass:function(b){var c=function(d,f){return a(f).test(d.className)};this.each(function(d){if(c(d,b)===false)d.className+=" "+b});return this},hasClass:function(b,c){var d=this;if(c===v&&this.elements.length==1)return a(b).test(d.elements[0].className);this.each(function(f){a(b).test(f.className)==true&&c(f)});return this},removeClass:function(b){if(b===v)this.each(function(d){d.className=""});else{var c=a(b);this.each(function(d){d.className=d.className.replace(c," ")})}return this},
css:function(b){var c=this;this.each(function(){for(var d in b)c.setStyle(d,b[d])});return this||c}});var e={},a=function(b){var c=e[b];if(!c){c=new RegExp("(?:^|\\s+)"+b+"(?:\\s+|$)");e[b]=c}return c}})();i.extend({xhr:function(e,a,b){if(!/^inner|outer|top|bottom|before|after$/.test(e)){b=a;a=e;e="inner"}var c=b?b:c;if(typeof b=="function"){c={};c.callback=b}var d=this;b=new XMLHttpRequest;var f=c.method||"get",o=c.async||false,l=c.data||null;b.queryString=l;b.open(f,a,o);if(c.headers)for(a=0;a<
c.headers.length;a++)b.setRequestHeader(c.headers[a].name,c.headers[a].value);b.onload=c.callback!=null?c.callback:function(){d.html(e,this.responseText)};b.send(l);return this}});(function(e,a){function b(g,n,k){return(g+(n-g)*k).toFixed(3)}function c(g,n,k){return g.substr(n,k||1)}function d(g,n,k){for(var m=2,h,j,r=[],t=[];h=3,j=arguments[m-1],m--;)if(c(j,0)=="r")for(j=j.match(/\d+/g);h--;)r.push(~~j[h]);else{if(j.length==4)j="#"+c(j,1)+c(j,1)+c(j,2)+c(j,2)+c(j,3)+c(j,3);for(;h--;)r.push(parseInt(c(j,
1+h*2,2),16))}for(;h--;){m=~~(r[h+3]+(r[h]-r[h+3])*k);t.push(m<0?0:m>255?255:m)}return"rgb("+t.join(",")+")"}function f(g){var n=parseFloat(g);g=g.replace(/^[\-\d\.]+/,"");return isNaN(n)?{v:g,f:d,u:""}:{v:n,f:b,u:g}}function o(g){var n={},k=p.length,m;l.innerHTML='<div style="'+g+'"></div>';for(g=l.childNodes[0].style;k--;)if(m=g[p[k]])n[p[k]]=f(m);return n}var l=s.createElement("div"),p="backgroundColor borderBottomColor borderBottomWidth borderLeftColor borderLeftWidth borderRightColor borderRightWidth borderSpacing borderTopColor borderTopWidth bottom color fontSize fontWeight height left letterSpacing lineHeight marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth opacity outlineColor outlineOffset outlineWidth paddingBottom paddingLeft paddingRight paddingTop right textIndent top width wordSpacing zIndex".split(" ");
a[e]=function(g,n,k){g=typeof g=="string"?s.getElementById(g):g;k=k||{};var m=o(n);n=g.currentStyle?g.currentStyle:getComputedStyle(g,null);var h,j={},r=+new Date,t=k.duration||200,x=r+t,y,A=k.easing||function(u){return-Math.cos(u*Math.PI)/2+0.5};for(h in m)j[h]=f(n[h]);y=setInterval(function(){var u=+new Date,B=u>x?1:(u-r)/t;for(h in m)g.style[h]=m[h].f(j[h].v,m[h].v,A(B))+m[h].u;if(u>x){clearInterval(y);k.after&&k.after()}},10)}})("emile",this)})();
